# Generated by Django 3.2.3 on 2021-05-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_imagebase64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imageBase64',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
