# Generated by Django 3.2.3 on 2021-05-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210526_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='male',
            field=models.FloatField(null=True),
        ),
    ]
