# Generated by Django 3.2.3 on 2021-05-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
